apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  selector:
    app: employee-service  # This should match the label used in the Deployment
  ports:
    - protocol: TCP
      port: 8080        # The port the service will expose
      targetPort: 8080  # The port your app is actually running on inside the container
      nodePort: 30001  # Expose it on port 30001 on the host
  type: NodePort
  
