apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  selector:
    app: employee-service  # This should match the label used in the Deployment
  ports:
    - protocol: TCP
      port: 8081        # The port the service will expose
      targetPort: 8081  # The port your app is actually running on inside the container
  type: ClusterIP  # By default, only accessible inside the cluster (use NodePort or LoadBalancer if you need external access)
